name: "Deb's Delicacies"
favicon: null
layout_spectrum: 0.4032755037769675
typography_spectrum: 0.0856713317334652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.42955715022981167
  lightness: 0.19416565843857825
  saturation: 0.8744672029279172
  rhythmicContrast: 0.17029607156291604
purpose: []
